{
 "title": "Similar Products",
 "tags": [
  "custom-metrics",
  "similar-products"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(\n  increase(api_requests_total{\n    flow=\"similar_products\",\n    type=~\"success|partial_success\",\n    type!~\"skipped_*\"\n  }[$__range])\n)\n/\nsum(\n  increase(api_requests_total{\n    flow=\"similar_products\",\n    type=~\"success|partial_success|error\",\n    type!~\"skipped_*\"\n  }[$__range])\n)",
     "legendFormat": "Uptime %"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow, type) (rate(api_requests_total{flow=~\"similar_products\", type!~\"skipped_not_found|skipped_error\"}[$__range]) * 60) or vector(0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Success or Partial Success",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow, type) (\n  increase(api_requests_total{\n    flow=\"similar_products\",\n    type=~\"success|partial_success\"\n  }[$__range])\n) or on(flow, type) vector(0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Skipped Products",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow, type) (rate(api_requests_total{flow=\"similar_products\", type=~\"skipped_.*\"}[$__range])) or vector(0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow) (\n  increase(api_requests_total{flow=\"similar_products\", type=\"error\"}[$__range])\n) or vector(0)",
     "legendFormat": "{{flow}}"
    }
   ]
  },
  { "title": "External Apis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow, type) (increase(api_requests_total{flow=~\"similar_ids|product_detail\"}[$__range]) * 60) or vector(0)",
     "legendFormat": "{{flow}}-{{type}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow) (increase(api_requests_total{flow=~\"product_detail|similar_ids\", type=\"error\"}[$__range]) * 60) or vector(0)",
     "legendFormat": "{{flow}}"
    }
   ]
  },
  {
   "title": "Fallback Executions - Similar Ids",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by (flow) (increase(api_requests_total{flow=~\"similar_ids\", type=\"fallback\"}[$__range])) or vector(0)",
     "legendFormat": "{{flow}} - Fallback"
    }
   ]
  }
 ]
}